In [ ]:
import numpy as np
import rpy2.robjects as ro
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()

In [ ]:
%load_ext rpy2.ipython

In [ ]:
%%R
library(devtools)
install_github("ericstrobl/RCIT")
library(RCIT)

In [ ]:
def convertPtoR(var):
    nr,nc = var.shape
    var_R = ro.r.matrix(var, nrow=nr, ncol=nc)
    return var_R

In [ ]:
ica_z= np.load('ica_z_te.npy')
pred_z= np.load('pred_z_te.npy')
true_z= np.load('true_z_te.npy')

ica_x= np.load('ica_x_te.npy')

d= ica_x.shape[1]
n= ica_x.shape[0]

In [ ]:
ica_x.shape

In [ ]:
for i in range(d):
    ro.r.assign("a_" + str(i), convertPtoR(np.reshape(ica_x[:,i], (n, 1))))

In [ ]:
%%R
x <- c(2,5,3,9,8,11,6)
count <- 0
for (val in x) {
if(val %% 2 == 0)  count = count+1
}
print(count)

In [ ]:
%%R
print(RCoT(a_0, a_0))
print(RCoT(a_0, a_1))
print(RCoT(a_1, a_1))

If a, b are dependent implies low p (p < 0.05) value

Contrapositive

High p (p>0.05) value implies a, b are independent

MCC is necessary for but sufficient for Permutation Identifiability

Bigger issue: Why ICA does not give us independence?

In [ ]:
x= np.random.rand(10,10)

In [ ]:
x= np.random.rand(2,2,2)
y= np.random.rand(2,2,2)

In [ ]:
np.sum(np.dot(x,y))

In [ ]:
x[:,:10].shape

In [6]:
import numpy as np
x= np.random.rand(2,2)
y= np.random.rand(2,2)

In [11]:
x*y.T

array([[0.07338752, 0.00320578],
       [0.02873946, 0.78167802]])

In [8]:
np.dot(x,y)

array([[0.0765933 , 0.05825506],
       [0.63600816, 0.81041748]])

In [12]:
x= np.random.rand(12)

In [13]:
x

array([0.90985131, 0.19572691, 0.05819496, 0.3825069 , 0.92692782,
       0.38153522, 0.25820476, 0.66045404, 0.77595121, 0.1878009 ,
       0.88117624, 0.38388844])

In [15]:
np.reshape(x, (3, 2, 2))

array([[[0.90985131, 0.19572691],
        [0.05819496, 0.3825069 ]],

       [[0.92692782, 0.38153522],
        [0.25820476, 0.66045404]],

       [[0.77595121, 0.1878009 ],
        [0.88117624, 0.38388844]]])