In [ ]:
import sys
import os
import argparse
import random
import copy
import os 

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [ ]:
seed= 10
random.seed(seed*10)
np.random.seed(seed*10) 

In [ ]:
data_dim= 2
num_tasks= 2
data_case= 'train'
train_size= 500
test_size= 100

if data_case == 'train':
    dataset_size= train_size
elif data_case == 'test':
    dataset_size= test_size

In [ ]:
# z= np.random.multivariate_normal(np.zeros(data_dim), np.eye(data_dim), dataset_size)

z= np.zeros((dataset_size, data_dim))
for i in range(data_dim):
    z[:, i]= np.random.laplace(0, 1, dataset_size)

#Transformation Functions
A1 = 0.5*np.random.rand(data_dim, data_dim)
A2 = 0.1*np.random.rand(data_dim, data_dim)
# A = 0.5*np.dot(A, A.transpose())
g = np.random.rand(data_dim, num_tasks)

# Sample x and y conditioned on the true latent z
x= np.matmul(z, A1) 
x= sigmoid(x)
# x= np.matmul(x, A2) 

y_c= 10
y= y_c*np.dot(z, g) + np.random.multivariate_normal(np.zeros(num_tasks), np.eye(num_tasks), dataset_size)

In [ ]:
np.std(y)

In [ ]:
plt.plot(np.sum(z, axis=1), y, '.')
# plt.xlabel('Latent z'aaa)
plt.xlabel('Data x')
plt.ylabel('Class Label y')

In [ ]:
plt.scatter(x[:, 0], x[:, 1])

In [ ]:
plt.scatter(z[:, 0], z[:, 1])

In [ ]:
x.shape

In [ ]:
plt.scatter(z[:, 0], x[:, 0])

In [ ]:
plt.scatter(z[:, 1], x[:, 1])

In [ ]:
np.mean(x)

In [ ]:
np.mean(z)

In [ ]:
Linear Regression Approximation between z and z_hat
[[  6.049838   10.150847  -21.826588    4.64385   -20.14035  ]
 [ 18.410906  -18.582125   -3.114055   -7.80445   -40.31162  ]
 [ 25.216389    4.2203956  12.034031  -15.12596   -23.0122   ]
 [-19.536152   -4.063727   -5.030505   10.849738   21.004234 ]
 [ 11.435124    4.5655494 -13.8809805  -1.9925435 -25.165222 ]]
Pred Error:  0.73246706

Post ICA Transformation
[[  0.70669599  -2.10270799  -2.8354034   -9.67472249  -8.90041929]
 [  0.10337354 -14.20602796   1.12044121   3.07013307   3.49415741]
 [ -0.59447488  -0.6962009   11.53939618  -2.04649542  -3.19800994]
 [ 10.82954496   1.52286244  -0.21092333   2.31641216   0.05143906]
 [ -3.7142119    1.11343704  -1.47110817   8.95021551 -11.65008971]]
Pred Error:  0.34984440210874906

In [ ]:
Linear Regression Approximation between z and z_hat
[[ -6.4244184   -6.927803    12.751406     6.0132165   -7.0129275 ]
 [-14.594966   -50.574974    75.35876     23.695633   -23.184736  ]
 [  1.9921079  -19.290482    26.089315     8.663521    -8.123807  ]
 [  6.5176144   12.724506   -21.75135     -5.857891     7.1009626 ]
 [ 13.102096    -7.434321     2.1955156    1.7568803   -0.65683466]]
Pred Error:  0.37177673

Post ICA Transformation
[[  0.25624251  13.59280582  -1.5791155   -2.95521855  -2.58575073]
 [  0.3269162   -0.10464218 -11.81800385   1.99640337   4.97575928]
 [ -0.04245726  -2.01236955   1.89301039  -9.28385086  11.15256887]
 [ 12.15785416   0.65547101   0.02761879  -0.60598284   3.64472506]
 [ -0.5767253    1.70970285   3.70593621   9.08926575   8.54484845]]
Pred Error:  0.35048875439927685

In [ ]:
Linear Regression Approximation between z and z_hat
[[-0.6529966  -1.7203861   0.9482305   1.9980783  -1.5809798 ]
 [-1.8587275  -7.8528523   3.2987664   3.899995    0.13496348]
 [-0.14222701 -3.8234925   2.346842    2.2162235  -0.9288836 ]
 [ 0.81748056  3.6788013  -2.337509   -0.8575886   0.35443935]
 [ 0.866105   -1.6341057  -0.1403562   0.17782313  0.60655063]]
Pred Error:  0.57224375

Post ICA Transformation
[[ -0.95776637   1.37624983 -12.39369366   1.36594289   2.73797685]
 [ 10.79137674   0.58886904  -1.86937009   3.60632231  -4.22609616]
 [ -1.12054093   3.56929828   3.01197652  10.3292583    4.90741342]
 [ -0.19764359  12.98817779   0.37968225  -4.35765619  -2.88557206]
 [  6.44575534  -1.63633801   0.77942827  -4.72127671  13.3372025 ]]
Pred Error:  0.3719719336722741
